# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='create time')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='finish time')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='start time')),
            ],
        ),
    ]
